esphome:
  name: led-${device_number}
  platformio_options:
    build_flags:
      #   - -D LWIP_LOOPIF_MULTICAST=1
      # - -D LWIP_IGMP=1
      - -DLWIP_DHCP_DOES_ACD_CHECK=0

  on_boot:
    then:
      - output.set_level:
          id: blue_out
          level: 0.1%
      - output.set_level:
          id: blue_out
          level: 0%
      - light.turn_on:
          id: main_light
          effect: "Sync from Server"

bk72xx:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev
    # loglevel: verbose

ota:
  - platform: esphome
    password: ""

# api:
#   password: ""

wifi:
  ssid: "TP-Link_69E4"
  password: "79970341"
  power_save_mode: none
  fast_connect: true
  reboot_timeout: 0s
  # fast_connect: True
  #  reboot_timeout: "5min"

# web_server:
#   port: 80

packages:
  common: !include ./common.yml

# Example RGB outputs (PWM)
output:
  - platform: libretiny_pwm # Use 'libretiny_pwm' platform for LibreTiny (ESP8266)
    id: red_out
    pin: P7
    frequency: 500 Hz
    max_power: 90%
  - platform: libretiny_pwm
    id: green_out
    pin: P8
    frequency: 500 Hz
    max_power: 100%
  - platform: libretiny_pwm
    id: blue_out
    pin: P9
    frequency: 500 Hz
    max_power: 50%
  - platform: libretiny_pwm
    id: white_out
    pin: P24
    frequency: 500 Hz
    max_power: 0%

light:
  - platform: rgb
    id: main_light
    name: "LEDVANCE Light"
    red: red_out
    green: green_out
    blue: blue_out
    default_transition_length: 0.1s
    effects:
      - random:
      - pulse:
      - strobe:
      - light_sync:
          name: "Sync from Server"
          light_sync_id: ls
