esphome:
  name: sdl
  friendly_name: sdl

  on_boot:
    then:
      - output.set_level:
          id: blue_out
          level: 0.1%
      - output.set_level:
          id: blue_out
          level: 0%
      - light.turn_on:
          id: main_light
          effect: "Sync from Server"

host:
network:

packages:
  common: !include common.yml

logger:
  level: DEBUG
  logs:
    light_sync: DEBUG
    light: INFO

output:
  - platform: template
    id: red_out
    type: float
    write_action:
      - lambda: |-
          // ESP_LOGD("FakeLight", "Fake red level: %.2f", state);
  - platform: template
    id: green_out
    type: float
    write_action:
      - lambda: |-
          // ESP_LOGD("FakeLight", "Fake green level: %.2f", state);
  - platform: template
    id: blue_out
    type: float
    write_action:
      - lambda: |-
          // ESP_LOGD("FakeLight", "Fake blue level: %.2f", state);

light:
  - platform: rgb
    id: main_light
    name: "Virtual Light"
    red: red_out
    green: green_out
    blue: blue_out
    default_transition_length: 0.1s
    effects:
      - random:
      - pulse:
      - strobe:
      - light_sync:
          name: "Sync from Server"
          light_sync_id: ls
# my_udp:
#   id: my_udp0
#   port: 4444
